create-network:
	docker network create payment

docker-mysql: create-network
	docker run -d --network payment --name mysql -td -p 3306:3306 -e MYSQL_ROOT_PASSWORD=cmpe172 mysql:8.0

mysql: 
	docker run -d --name mysql -td -p 3306:3306 -e MYSQL_ROOT_PASSWORD=cmpe172 mysql:8.0

excute-mysql:
	docker exec -it mysql bash

