
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-backend 
  labels:
    app: grocery-backend 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grocery-backend 
  template:
    metadata:
      labels:
        app: grocery-backend 
    spec:
      containers:
      - name: grocery-backend 
        image: xuefeng89/grocery-backend:v1   
        ports:
        - containerPort: 8080
        env:
          - name: MYSQL_HOST
            valueFrom:
              secretKeyRef:
                  name: mysql-host
                  key: dbhost
          - name: MYSQL_USER_NAME
            valueFrom:
              secretKeyRef:
                  name: mysql-user-pass
                  key: username
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: mysql-user-pass
                  key: password
          





      